name: Build and Deploy Sphinx

on:
  push:
    branches: [main,SphinxFix]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - run: pip install --upgrade pip sphinx -r SphinxDoc/sphinx-requirements.txt

      - run: rm -rf SphinxDoc/api

      - run: sphinx-apidoc -o SphinxDoc/api SourceCode/

      - run: |
          cd SphinxDoc
          make html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: SphinxDoc/_build/html

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
